# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coef_cal_sc <- function(Y, S, X) {
    .Call(`_caratMULT_coef_cal_sc`, Y, S, X)
}

coef_cal_ss <- function(Y, S, A, X) {
    .Call(`_caratMULT_coef_cal_ss`, Y, S, A, X)
}

coef_cal_sc_new <- function(Y, S, X, pS, pi_as) {
    .Call(`_caratMULT_coef_cal_sc_new`, Y, S, X, pS, pi_as)
}

