// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// coef_cal_sc
arma::vec coef_cal_sc(arma::vec Y, arma::vec S, arma::mat X);
RcppExport SEXP _caratMULT_coef_cal_sc(SEXP YSEXP, SEXP SSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(coef_cal_sc(Y, S, X));
    return rcpp_result_gen;
END_RCPP
}
// coef_cal_ss
arma::mat coef_cal_ss(arma::vec Y, arma::vec S, arma::vec A, arma::mat X);
RcppExport SEXP _caratMULT_coef_cal_ss(SEXP YSEXP, SEXP SSEXP, SEXP ASEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(coef_cal_ss(Y, S, A, X));
    return rcpp_result_gen;
END_RCPP
}
// coef_cal_sc_new
arma::mat coef_cal_sc_new(arma::vec Y, arma::vec S, arma::mat X, arma::vec pS, arma::vec pi_as);
RcppExport SEXP _caratMULT_coef_cal_sc_new(SEXP YSEXP, SEXP SSEXP, SEXP XSEXP, SEXP pSSEXP, SEXP pi_asSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pS(pSSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi_as(pi_asSEXP);
    rcpp_result_gen = Rcpp::wrap(coef_cal_sc_new(Y, S, X, pS, pi_as));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_caratMULT_coef_cal_sc", (DL_FUNC) &_caratMULT_coef_cal_sc, 3},
    {"_caratMULT_coef_cal_ss", (DL_FUNC) &_caratMULT_coef_cal_ss, 4},
    {"_caratMULT_coef_cal_sc_new", (DL_FUNC) &_caratMULT_coef_cal_sc_new, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_caratMULT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
